# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies, 
# and to customize the application with features that require configuration settings.

# You can use `rake secret` to generate a secure secret key.

development:
  secret_key_base: 56039bcc53cc1b325ca94ef816a0464d5f9da8af8f206720d374b0101180b9dbfb489acac353ef57238bf4b03091903e01e175e60c5beb6d93baa263379dc9d6

test:
  secret_key_base: 5417a22cccef7f5c8fe19160816f39283257ca06120a7f2c94acfb6d55be316f72ab05f95793bf23d28a0ba1b5e6fe5e21a83c55e2bdb80971ff3253d7a7049b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>